name: flutter_todo
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1

  # Routing
  auto_route: 8.0.0

  # State Management
  flutter_riverpod: 2.5.1
  hooks_riverpod: 2.5.1
  riverpod_annotation: 2.3.5
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1

  # Data
  rxdart: 0.27.7
  sembast: 3.7.1
  sembast_web: 2.3.0
  flutter_secure_storage: 9.0.0
  # Network
  dio: 5.4.2+1

  # Widgets & UI
  flutter_svg: 2.0.10+1
  google_fonts: 6.2.1
  cached_network_image: 3.3.1

  # Testing

  # Misc
  platform: 3.1.4
  path_provider: 2.1.2
  path: 1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2
  auto_route_generator: 8.0.0
  custom_lint: 0.6.4
  riverpod_generator: 2.4.0
  riverpod_lint: 2.3.10
  freezed: 2.4.7
  json_serializable: 6.7.1
  build_runner: 2.4.8

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
